In [1]:
import pandas as pd

# Data Exploration for Black Friday dataset 
Celebration - November 27th

In [2]:
df_bf = pd.read_csv('output/BlackFriday.csv')

/usr/local/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3051: DtypeWarning: Columns (12) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [3]:
df_bf.head()

,Unnamed: 0,Unnamed: 0.1,date,favorites,followers,hashtags,id,location,query,retweets,text,url,urls,user
0,0,0.0,2020-11-28 09:11:15,1102,55420,"[{'text': 'PS5', 'indices': [28, 32]}, {'text'...",1332613012767858690,España,BlackFriday,2207,💣🔥BOOOOMBA 🔥💣\nSORTEAMOS una #PS5 para celebra...,NaN,"[{'url': 'https://t.co/8yOAahMJxW', 'expanded_...",WortenES
1,1,1.0,2020-11-29 09:51:13,2012,12508,[],1332985456691204101,Santiago de Compostela,BlackFriday,438,Los conciertos contagian pero el blackfriday n...,NaN,[],novcarminha
2,2,2.0,2020-11-28 03:27:53,237,155974,"[{'text': 'BlackFriday', 'indices': [23, 35]}]",1332526601528102912,"USA, España & Latinoamerica",BlackFriday,218,La mejor inversión del #BlackFriday es Platzi ...,NaN,"[{'url': 'https://t.co/DVk0LwtZdj', 'expanded_...",platzi
3,3,3.0,2020-11-29 15:22:45,0,398,[],1333068890109317127,Radio 3 - España,BlackFriday,438,RT @novcarminha: Los conciertos contagian pero...,NaN,[],Rascaypicas
4,4,4.0,2020-11-29 15:22:30,0,175,"[{'text': 'PlayStation5', 'indices': [65, 78]}...",1333068829879054340,NaN,BlackFriday,2433,RT @WortenES: 🔥🔥SORTEO BOMBA ESPECIAL BLACK FR...,NaN,[],luisleiving

In [4]:
# How many records are there?
df_bf.shape

(140549, 14)

In [5]:
# How many duplicated are there?
df_bf.duplicated().sum()

76

In [6]:
#Looking for null values
df_bf.isnull().sum()

Unnamed: 0           0
Unnamed: 0.1     83539
date                 0
favorites            0
followers            0
hashtags             0
id                   0
location         44063
query                0
retweets             0
text                 0
url                 10
urls            140539
user                 0
dtype: int64

In [7]:
#Reducing the dataframe to only key columns

df_bf = df_bf[['query', 'id', 'date', 'user', 'followers', 'text', 'hashtags', 'url', 'urls', 'favorites', 'retweets', 'location']]

In [8]:
df_bf.head()

,query,id,date,user,followers,text,hashtags,url,urls,favorites,retweets,location
0,BlackFriday,1332613012767858690,2020-11-28 09:11:15,WortenES,55420,💣🔥BOOOOMBA 🔥💣\nSORTEAMOS una #PS5 para celebra...,"[{'text': 'PS5', 'indices': [28, 32]}, {'text'...",NaN,"[{'url': 'https://t.co/8yOAahMJxW', 'expanded_...",1102,2207,España
1,BlackFriday,1332985456691204101,2020-11-29 09:51:13,novcarminha,12508,Los conciertos contagian pero el blackfriday n...,[],NaN,[],2012,438,Santiago de Compostela
2,BlackFriday,1332526601528102912,2020-11-28 03:27:53,platzi,155974,La mejor inversión del #BlackFriday es Platzi ...,"[{'text': 'BlackFriday', 'indices': [23, 35]}]",NaN,"[{'url': 'https://t.co/DVk0LwtZdj', 'expanded_...",237,218,"USA, España & Latinoamerica"
3,BlackFriday,1333068890109317127,2020-11-29 15:22:45,Rascaypicas,398,RT @novcarminha: Los conciertos contagian pero...,[],NaN,[],0,438,Radio 3 - España
4,BlackFriday,1333068829879054340,2020-11-29 15:22:30,luisleiving,175,RT @WortenES: 🔥🔥SORTEO BOMBA ESPECIAL BLACK FR...,"[{'text': 'PlayStation5', 'indices': [65, 78]}...",NaN,[],0,2433,NaN

In [9]:
#Order the dataframe by date from oldest to newest tweet
df_bf.sort_values('date', ascending=True).head()

,query,id,date,user,followers,text,hashtags,url,urls,favorites,retweets,location
138763,BlackFriday,1330426275572445184,2020-11-22 08:21:56,la_gando,0,Participa para tener la oportunidad de ganar i...,"[{'text': 'DJI', 'indices': [66, 70]}]","[{'url': 'https://t.co/iWzlJ1KFMZ', 'expanded_...",NaN,1,0,NaN
138781,BlackFriday,1330426275572445184,2020-11-22 08:21:56,la_gando,0,Participa para tener la oportunidad de ganar i...,"[{'text': 'DJI', 'indices': [66, 70]}]","[{'url': 'https://t.co/iWzlJ1KFMZ', 'expanded_...",NaN,1,0,NaN
138782,BlackFriday,1330426275572445184,2020-11-22 08:21:56,la_gando,0,Participa para tener la oportunidad de ganar i...,"[{'text': 'DJI', 'indices': [66, 70]}]","[{'url': 'https://t.co/iWzlJ1KFMZ', 'expanded_...",NaN,1,0,NaN
138783,BlackFriday,1330426275572445184,2020-11-22 08:21:56,la_gando,0,Participa para tener la oportunidad de ganar i...,"[{'text': 'DJI', 'indices': [66, 70]}]","[{'url': 'https://t.co/iWzlJ1KFMZ', 'expanded_...",NaN,1,0,NaN
138784,BlackFriday,1330426275572445184,2020-11-22 08:21:56,la_gando,0,Participa para tener la oportunidad de ganar i...,"[{'text': 'DJI', 'indices': [66, 70]}]","[{'url': 'https://t.co/iWzlJ1KFMZ', 'expanded_...",NaN,1,0,NaN

# Key info from the dataframe

In [10]:
#The most engaging tweet by retweets
df_bf[(df_bf['retweets'] == df_bf["retweets"].max())]

,query,id,date,user,followers,text,hashtags,url,urls,favorites,retweets,location
57105,BlackFriday,1332522796199538688,2020-11-28 03:12:46,BoyBoy10730758,47,RT @ChrisDiamond_x: En BlackFriday voy a hacer...,[],"[{'url': 'https://t.co/7dMjqOKHMK', 'expanded_...",NaN,0,4324,NaN
115813,BlackFriday,1331409302209269761,2020-11-25 01:28:08,Nnnnnnn996969,185,RT @ChrisDiamond_x: En BlackFriday voy a hacer...,[],"[{'url': 'https://t.co/7dMjqOKHMK', 'expanded_...",NaN,0,4324,"จ.พระนครศรีอยุธยา, ประเทศไทย"

In [11]:
#Top 5 tweets by retweets
df_bf.nlargest(5, 'retweets')

,query,id,date,user,followers,text,hashtags,url,urls,favorites,retweets,location
57105,BlackFriday,1332522796199538688,2020-11-28 03:12:46,BoyBoy10730758,47,RT @ChrisDiamond_x: En BlackFriday voy a hacer...,[],"[{'url': 'https://t.co/7dMjqOKHMK', 'expanded_...",NaN,0,4324,NaN
115813,BlackFriday,1331409302209269761,2020-11-25 01:28:08,Nnnnnnn996969,185,RT @ChrisDiamond_x: En BlackFriday voy a hacer...,[],"[{'url': 'https://t.co/7dMjqOKHMK', 'expanded_...",NaN,0,4324,"จ.พระนครศรีอยุธยา, ประเทศไทย"
68318,BlackFriday,1332377215217115136,2020-11-27 17:34:17,cotiess1,173,RT @CarrefourGaming: ⚠ Concurso\n¡Queremos cel...,"[{'text': 'BlackFriday', 'indices': [54, 66]}]",[],NaN,0,4120,NaN
74126,BlackFriday,1332334486072201216,2020-11-27 14:44:29,javifch41,1,RT @CarrefourGaming: ⚠ Concurso\n¡Queremos cel...,"[{'text': 'BlackFriday', 'indices': [54, 66]}]",[],NaN,0,4120,NaN
75950,BlackFriday,1332323102810894337,2020-11-27 13:59:15,Nima1224_,59,RT @CarrefourGaming: ⚠ Concurso\n¡Queremos cel...,"[{'text': 'BlackFriday', 'indices': [54, 66]}]",[],NaN,0,4120,"Palma de Mallorca , España"

In [12]:
#The most influencer by number of followers
df_bf[(df_bf['followers'] == df_bf["followers"].max())]

,query,id,date,user,followers,text,hashtags,url,urls,favorites,retweets,location
134447,BlackFriday,1330809565223428098,2020-11-23 09:45:00,FCBarcelona_es,15948024,📢 ¡Comienza el Barça #BlackFriday! 🔵🔴\n😱 ¡El m...,"[{'text': 'BlackFriday', 'indices': [21, 33]}]",[],NaN,696,38,📲 BarçaTV+ 👉

# Data Exploration for Cyber Monday dataset
Celebration - November 30th

In [13]:
df_cm = pd.read_csv('output/CyberMonday.csv')
df_cm.head()

,Unnamed: 0,Unnamed: 0.1,date,favorites,followers,hashtags,id,location,query,retweets,text,url,urls,user
0,0,0.0,2020-11-24 14:02:27,23,2208088,[],1331236744767926275,"Guayaquil, Ecuador",CyberMonday,17,Cámara de Comercio de Guayaquil anuncia cuatro...,NaN,"[{'url': 'https://t.co/m07aK2u47s', 'expanded_...",eluniversocom
1,1,1.0,2020-11-26 17:15:04,22,61206,"[{'text': 'BlackFriday', 'indices': [51, 63]},...",1332009994905071618,España,CyberMonday,20,No seas tu el chollo de los ciberdelincuentes ...,NaN,"[{'url': 'https://t.co/T2FzUbDGca', 'expanded_...",INCIBE
2,2,2.0,2020-11-26 07:00:23,22,61206,"[{'text': 'BlackFriday', 'indices': [14, 26]},...",1331855304699604992,España,CyberMonday,21,"¡Buenos días! #BlackFriday, #CyberMonday, #Nav...",NaN,"[{'url': 'https://t.co/nOUN4HJqfx', 'expanded_...",INCIBE
3,3,3.0,2020-11-29 19:12:12,0,358,"[{'text': 'ofertas', 'indices': [52, 60]}, {'t...",1333126635239956481,NaN,CyberMonday,0,"Las fechas navideñas ya están aquí, y con ella...",NaN,"[{'url': 'https://t.co/MnHjVJEO3I', 'expanded_...",HogarCom
4,4,4.0,2020-11-29 19:10:02,0,104,[],1333126089590321153,El Averno,CyberMonday,2,"RT @0xWORD: Como todos los años, desde hoy a l...",NaN,[],InformDelAverno

In [14]:
# How many records are there?
df_cm.shape

(36779, 14)

In [15]:
# How many duplicated are there?
df_cm.duplicated().sum()

0

In [16]:
#Looking for null values
df_cm.isnull().sum()

Unnamed: 0          0
Unnamed: 0.1     2269
date                0
favorites           0
followers           0
hashtags            0
id                  0
location         8878
query               0
retweets            0
text                0
url                10
urls            36769
user                0
dtype: int64

In [17]:
#Reducing the dataframe to only key columns

df_cm = df_cm[['query', 'id', 'date', 'user', 'followers', 'text', 'hashtags', 'url', 'urls', 'favorites', 'retweets', 'location']]

In [18]:
#Order the dataframe by date from oldest to newest tweet
df_cm.sort_values('date', ascending=True).head()

,query,id,date,user,followers,text,hashtags,url,urls,favorites,retweets,location
36778,CyberMonday,1330535669249269762,2020-11-22 15:36:38,franchusketa,245,@soymariaiglesia @SolBA Las intiman pero sigue...,[],"[{'url': 'https://t.co/Z7scqItEr2', 'expanded_...",NaN,1,0,"Buenos Aires, Argentina"
36777,CyberMonday,1330541049329164288,2020-11-22 15:58:01,xtal_b,3641,RT @AnnaCLXY: Cuidado estos días con las supue...,[],[],NaN,0,34,"Paris, Barcelona, Bruxelles"
36776,CyberMonday,1330543847714287616,2020-11-22 16:09:08,amalitaeonni,94,Cuando Davis es puro amor ❤️💔 \nMuy pronto les...,[],"[{'url': 'https://t.co/mrWyo3ZmZo', 'expanded_...",NaN,0,0,Sunshine State
36775,CyberMonday,1330561933678940160,2020-11-22 17:21:00,compraloloenvio,75,"Sudaderas muy combinables y cómodas, para ti o...",[],"[{'url': 'https://t.co/4N7Y8pbiEO', 'expanded_...",NaN,0,0,México
36774,CyberMonday,1330568516358070276,2020-11-22 17:47:09,HeyJonasForever,14049,Mis papás están aprendiendo a usar la olla a p...,[],[],NaN,1,0,CHILE 🇨🇱

# Key info from the dataframe

In [19]:
#The most engaging tweet by retweets
df_cm[(df_cm['retweets'] == df_cm["retweets"].max())]

,query,id,date,user,followers,text,hashtags,url,urls,favorites,retweets,location
36466,CyberMonday,1333819252705550337,2020-12-01 17:04:25,mastangao,38,RT @WortenES: 🔥ÚLTIMO DÍA de SORTEO 🔥\nEl #Cyb...,"[{'text': 'CyberMonday', 'indices': [41, 53]},...",[],NaN,0,1175,NaN
36470,CyberMonday,1333818430152175618,2020-12-01 17:01:09,guillegodoy9,121,RT @WortenES: 🔥ÚLTIMO DÍA de SORTEO 🔥\nEl #Cyb...,"[{'text': 'CyberMonday', 'indices': [41, 53]},...",[],NaN,0,1175,NaN

In [20]:
#Top 5 tweets by retweets
df_cm.nlargest(5, 'retweets')

,query,id,date,user,followers,text,hashtags,url,urls,favorites,retweets,location
36466,CyberMonday,1333819252705550337,2020-12-01 17:04:25,mastangao,38,RT @WortenES: 🔥ÚLTIMO DÍA de SORTEO 🔥\nEl #Cyb...,"[{'text': 'CyberMonday', 'indices': [41, 53]},...",[],NaN,0,1175,NaN
36470,CyberMonday,1333818430152175618,2020-12-01 17:01:09,guillegodoy9,121,RT @WortenES: 🔥ÚLTIMO DÍA de SORTEO 🔥\nEl #Cyb...,"[{'text': 'CyberMonday', 'indices': [41, 53]},...",[],NaN,0,1175,NaN
36077,CyberMonday,1333714831854219265,2020-12-01 10:09:29,DMZDESSIGNS,378,RT @WortenES: 🔥ÚLTIMO DÍA de SORTEO 🔥\nEl #Cyb...,"[{'text': 'CyberMonday', 'indices': [41, 53]},...",[],NaN,0,1174,NaN
36097,CyberMonday,1333717266127597571,2020-12-01 10:19:10,mtrujillo2000,221,RT @WortenES: 🔥ÚLTIMO DÍA de SORTEO 🔥\nEl #Cyb...,"[{'text': 'CyberMonday', 'indices': [41, 53]},...",[],NaN,0,1174,"Córdoba, España"
36126,CyberMonday,1333729386445611008,2020-12-01 11:07:19,tenysamy,373,RT @WortenES: 🔥ÚLTIMO DÍA de SORTEO 🔥\nEl #Cyb...,"[{'text': 'CyberMonday', 'indices': [41, 53]},...",[],NaN,0,1174,jaen

In [21]:
#The most influencer by number of followers
df_cm[(df_cm['followers'] == df_cm["followers"].max())]

,query,id,date,user,followers,text,hashtags,url,urls,favorites,retweets,location
35331,CyberMonday,1333561514058534914,2020-12-01 00:00:15,Telemundo,2969932,🛍 Lanzan recomendaciones para evitar estafas d...,"[{'text': 'CyberMonday', 'indices': [68, 80]}]","[{'url': 'https://t.co/89k3FGTDzY', 'expanded_...",NaN,8,0,"Miami, FL"

In [22]:
#Top 5 influencer by followers and retweets
df_cm.nlargest(5, ['followers', 'retweets'])

,query,id,date,user,followers,text,hashtags,url,urls,favorites,retweets,location
35331,CyberMonday,1333561514058534914,2020-12-01 00:00:15,Telemundo,2969932,🛍 Lanzan recomendaciones para evitar estafas d...,"[{'text': 'CyberMonday', 'indices': [68, 80]}]","[{'url': 'https://t.co/89k3FGTDzY', 'expanded_...",NaN,8,0,"Miami, FL"
8932,CyberMonday,1331958403825065991,2020-11-26 13:50:04,bbva,2519044,¡El #BlackFriday y el #CyberMonday ya están aq...,"[{'text': 'BlackFriday', 'indices': [4, 16]}, ...","[{'url': 'https://t.co/Z1cks2UzCx', 'expanded_...",NaN,6,2,NaN
10432,CyberMonday,1331958403825065991,2020-11-26 13:50:04,bbva,2519044,¡El #BlackFriday y el #CyberMonday ya están aq...,"[{'text': 'BlackFriday', 'indices': [4, 16]}, ...","[{'url': 'https://t.co/Z1cks2UzCx', 'expanded_...",NaN,6,2,NaN
11932,CyberMonday,1331958403825065991,2020-11-26 13:50:04,bbva,2519044,¡El #BlackFriday y el #CyberMonday ya están aq...,"[{'text': 'BlackFriday', 'indices': [4, 16]}, ...","[{'url': 'https://t.co/Z1cks2UzCx', 'expanded_...",NaN,6,2,NaN
13432,CyberMonday,1331958403825065991,2020-11-26 13:50:04,bbva,2519044,¡El #BlackFriday y el #CyberMonday ya están aq...,"[{'text': 'BlackFriday', 'indices': [4, 16]}, ...","[{'url': 'https://t.co/Z1cks2UzCx', 'expanded_...",NaN,6,2,NaN